.equ    EXCEPTION_RESET, 0
.equ    EXCEPTION_UND, 1
.equ    EXCEPTION_SVC, 2
.equ    EXCEPTION_PABT, 3
.equ    EXCEPTION_DABT, 4
.equ    EXCEPTION_RESERVED, 5
.equ    EXCEPTION_IRQ, 6
.equ    EXCEPTION_FIQ, 7
